apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrohit-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retrohit
  template:
    metadata:
      labels:
        app: retrohit
    spec:
      containers:
      - name: retrohit
        image: retrohit/java-app:latest
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: retrohit-service
spec:
  selector:
    app: retrohit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: NodePort
