apiVersion: apps/v1
kind: Deployment
metadata:
  name: retrohit-app
  namespace: retrohit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retrohit
  template:
    metadata:
      labels:
        app: retrohit
    spec:
      containers:
        - name: retrohit
          image: saicharan6771/retrohit:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: retrohit-service
  namespace: retrohit
spec:
  selector:
    app: retrohit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
