apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retrohit-ingress
  namespace: retrohit
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: retrohit-service
            port:
              number: 80
