apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retrohit-ingress
  namespace: retrohit
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: retrohit.yourdomain.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: retrohit-service
                port:
                  number: 80
