apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: retrohit-ingress
  namespace: retrohit
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/default-backend: retrohit-service
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: retrohit-service
                port:
                  number: 80
