apiVersion: v1
kind: Service
metadata:
  name: retrohit-service
  namespace: retrohit
spec:
  selector:
    app: retrohit
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
